### ISSUE TITLE
6.0 Roadmap

### ISSUE THREAD

**Issue by wbrowar** [wbrowar/WB-Starter#23]
- [x] Add front-end/back-end options to installer
  - Determine if NodeJS is needed for back-end CMS install
- [x] Pull non-Node related configuration out of package.json and move to config JS file
- [x] Add Tailwind CSS into front-end processes
  - [x] Remove/update utility classes
  - [x] Update Vue components to use tailwind where necessary
    - [x] Icon SVG
    - [ ] Wrapper
- [x] Clean up `_starter` directory
  - [x] Organize folders by node scripts
  - [x] Sort out `install` folder
- [x] Split favicon processes into own Node script
- [x] Remove stupid DAS keyboard stuff
- [ ] Prep for Vue 3?
- [ ] Look into front-end automated testing (Jest?)

**Comment by wbrowar** [comment]
Although Tailwind introduces a way to do a lot of component styling with Tailwind classes, there are are some places where CSS components could still be valid. Should CSS components still follow a BEM-like syntax or should they look more like Tailwind classes, or something else?

For example:

| BEM | Tailwind | Tailwind Abbreviated | Mixed |
|---|---|---|---|
| `c_buttons` | `c-buttons` | `c-btns` | `c_buttons` |
| `c_buttons--center` | `c-buttons-center` | `c-btns-center` | `c_buttons-center` |

**Comment by wbrowar** [comment]
I'm thinking that since Tailwind covers Flex and Grid (in 2.1) so well that we can remove the Grid and Flex Vue components.
